//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Xunit;
using System.ComponentModel.DataAnnotations;

namespace final_version2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rest
    {
        public int RestaurantId { get; set; }

        [Required(ErrorMessage = "Please enter a restaurant name.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter the description of restaurant.")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Please enter the longitude of restaurant.")]
        public decimal Longitude { get; set; }

        [Required(ErrorMessage = "Please enter the latitude of restaurant.")]
        public decimal Latitude { get; set; }
    }
}
